--INSERT DE MENU
INSERT INTO MENU (description) VALUES ('INFANTIL');
INSERT INTO MENU (description) VALUES ('COMÚN');
INSERT INTO MENU (description) VALUES ('CELÍACO');
INSERT INTO MENU (description) VALUES ('VEGETARIANO');
INSERT INTO MENU (description) VALUES ('VEGANO');
INSERT INTO MENU (description) VALUES ('ALERGICO');

--INSERT DE TIPOS DE EVENTOS
INSERT INTO TYPE_EVENT (description) VALUES ('EGRESADOS');
INSERT INTO TYPE_EVENT (description) VALUES ('CASAMIENTO');
INSERT INTO TYPE_EVENT (description) VALUES ('BAUTISMO');

--INSERT DE ESCUELAS PARA PROBAR
INSERT INTO SCHOOL (name) VALUES ('ESC.N°77 MAESTROS PUNTANOS ');
INSERT INTO SCHOOL (name) VALUES ('ESC.N°9 ESTEBAN ADARO ');
INSERT INTO SCHOOL (name) VALUES ('COLEGIO N° 12 R.CARRILLO');